volumes:
  db_data:
  kong_data:

networks:
  mynetwork:

services:
  server:
    build:
      context: .
      target: final
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    environment:
      - ConnectionStrings__DefaultConnection=Server=tcp:db,1433;Database=master;User Id=sa;Password=MyTe&TP@88wor^;TrustServerCertificate=True

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    ports:
      - "8095:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyTe&TP@88wor^
    restart: always
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - mynetwork

  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpassword
    ports:
      - "5432:5432"
    restart: always
    networks:
      - mynetwork
    volumes:
      - kong_data:/var/lib/postgresql/data

  kong-migrations:
    image: kong:latest
    container_name: kong-migrations
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpassword
    command: "kong migrations bootstrap"
    networks:
      - mynetwork

  kong:
    image: kong:latest
    container_name: kong
    depends_on:
      - kong-migrations
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpassword
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    volumes:
      - ./kong.yml:/etc/kong/kong.yml  # 📌 PridanýS volume pre kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - mynetwork

  konga:
    image: pantsel/konga:latest
    container_name: konga
    restart: always
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - TOKEN_SECRET=supersecret
    depends_on:
      - kong
    networks:
      - mynetwork
